language: julia
os:
    - linux
    - osx
julia:
    - release
    - nightly
notifications:
    email: false
after_success:
    - if [ $TRAVIS_JULIA_VERSION = "nightly" ]; then julia -e 'cd(Pkg.dir("BinDeps")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'; fi
